In [26]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
import math
df.bedrooms.median()

3.5

In [16]:
df = pd.read_excel("D:\\Data science\\Machine learning\\multi_linear_regression\\prices.xlsx")
df.fillna(4,inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [14]:
model = linear_model.LinearRegression()
model.fit(df.drop('price',axis='columns'),df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
model.predict([[3000,3,40]])

array([393849.40026655])

In [21]:
model.predict([[2500,4,5]])

array([614003.22079076])

In [19]:
model.coef_

array([   165.47645491, -72491.11505997, -10725.23322968])

In [20]:
model.intercept_

543902.7099067079

# Exercise-2

In [30]:
from word2number import w2n

In [27]:
exe_df = pd.read_csv("D:\\Data science\\Machine learning\\multi_linear_regression\\hiring.csv")
exe_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [48]:
exe_df.experience = exe_df.experience.fillna('Zero')
exe_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [50]:
# exe_df.experience = exe_df.experience.apply(w2n.word_to_num)

In [51]:
import math
exe_df["test_score(out of 10)"].median()

8.0

In [55]:
exe_df["test_score(out of 10)"] = exe_df["test_score(out of 10)"].fillna(8)
exe_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [57]:
exe_model = linear_model.LinearRegression()
exe_model.fit(exe_df.drop("salary($)",axis='columns'), exe_df["salary($)"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [58]:
exe_model.predict([[2,9,6]])

array([53205.96797671])

In [59]:
exe_model.predict([[12,10,10]])

array([92002.18340611])

In [61]:
exe_df.to_csv('D:\\Data science\\Machine learning\\multi_linear_regression\\hiring.csv')