In [19]:
import numpy as np
import time
a1 = np.array([[1,2],[0,1]])
a2 = np.array([[8,7],[4,6]])

total = a2 - a1
print(total)
print("How to define Two deminstion array:",a2[1][1])
print("Item size is:",a1.itemsize)
a1.ndim

[[7 5]
 [4 5]]
How to define Two deminstion array: 6
Item size is: 4


2

In [22]:
import numpy as np
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [28]:
import numpy as np
np.arange(1,5)
np.arange(1,5,2)


array([1, 3])

In [31]:
import numpy as np
a = np.array([[1,2],[0,1]])
a.min()
a.max()

4

In [35]:
import numpy as np
a = np.array([[1,2],[0,1]])
a.sum()
a.sum(axis=0)  #Column sum
a.sum(axis=1)  #Row sum

array([3, 1])

In [54]:
a = np.array([1,2,3,4,5])
np.std(a)

1.4142135623730951

In [55]:
a = np.array([1,2,3,4,5])
a[3:4]

array([4])